export const LOAD_STORES_SUCCESS = 'LOAD_STORES_SUCCESS';
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS';
export const REQUEST_SHOPS = 'REQUEST_SHOPS';
